# Generated by Django 3.0.3 on 2020-03-02 10:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=128, verbose_name='Name')),
                ('person_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender')),
                ('person_dob', models.DateField(verbose_name='Date of birth')),
                ('person_age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)], verbose_name='Age of registration')),
                ('person_register', models.DateTimeField(auto_now=True, null=True, verbose_name='Registration timestamp')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='demo.Person')),
            ],
            bases=('demo.person', models.Model),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='demo.Person')),
                ('teacher_school', models.CharField(choices=[('SED', 'Education'), ('SOE', 'Engineering'), ('SAS', 'Arts and Sciences'), ('SLG', 'Law and Governance'), ('SBE', 'Business and Economics'), ('SHCP', 'Healthcare Professions'), ('SAFAD', 'Architecture, Fine Arts and Design')], max_length=5, verbose_name='School')),
            ],
            bases=('demo.person', models.Model),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(max_length=32, verbose_name='Course code')),
                ('course_school', models.CharField(choices=[('SED', 'Education'), ('SOE', 'Engineering'), ('SAS', 'Arts and Sciences'), ('SLG', 'Law and Governance'), ('SBE', 'Business and Economics'), ('SHCP', 'Healthcare Professions'), ('SAFAD', 'Architecture, Fine Arts and Design')], max_length=5, verbose_name='School')),
                ('course_teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='demo.Teacher', verbose_name='Course teacher')),
                ('course_enrollees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Student', verbose_name='Course enrollees')),
            ],
        ),
    ]
