# Generated by Django 3.0.3 on 2020-03-02 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='person_age',
        ),
    ]
